### ISSUE TITLE
ModuleNotFoundError: No module named 'Module'

### ISSUE THREAD

**Issue by huang7017** [peterinhouse123/LineageM_Bot#1]
你好我參考了你的一些寫法 但是我的錯誤都卡在from Module import adb
adb那部分因為我打算搭配openCV使用 所以把功能改成截圖能使用了

**Comment by peterinhouse123** [comment]
hi

剛在FB上和你對談過了，在這邊也為你解答以上，以後說不定也會有人遇到這個問題。

Python針對 from的目錄，有先判斷是否存在 init.py的文件，如果不存在時常會引用失敗

如果遇到這個，目錄明明存在引用就不行，請記得在目錄裡建一個 init.py 的空白文件
問題就能解決囉
